version: '3.8'

services:
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '8080:80'
    volumes:
      - ../src:/var/www/html
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
